#! /bin/sh

set -e

. /usr/share/debconf/confmodule

F=`mktemp`
RETV=0
fgdiag-disktest-verification > $F || RETV=$?

if [ "$RETV" != "0" ]; then
  db_settitle debian-installer/fgdiag-disktest-verification-udeb/title
  db_subst fgdiag-disktest-verification-udeb/drive_not_wiped OUTPUT "$(cat $F)"
  db_input critical fgdiag-disktest-verification-udeb/drive_not_wiped || [ $? -eq 30 ]
  db_go || exit 10
  db_get fgdiag-disktest-verification-udeb/drive_not_wiped
  if [ "$RET" != true ]; then
    rm -f $F
    exit 10
  fi
fi

rm -f $F
exit 0
